### ISSUE TITLE
Error when running train.py

### ISSUE THREAD

**Issue by ShilinC** [kevin-kaixu/grass_pytorch#3]
```
Using CUDA on GPU  0
Loading data ...... DONE
Start training ...... 
     Time    Epoch     Iteration    Progress(%)  ReconLoss  KLDivLoss  TotalLoss
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    total_loss = dec_fold.apply(decoder, [dec_fold_nodes, kld_fold_nodes])
  File "/home/XXX/anaconda3/envs/Py36_PT/lib/python3.6/site-packages/torchfold-0.1.0-py3.6.egg/torchfold/torchfold.py", line 165, in apply
  File "/home/XXX/Documents/3D_Hier_Ins/grass_pytorch/grassmodel.py", line 227, in classifyLossEstimator
    return torch.cat([self.creLoss(l.unsqueeze(0), gt).mul(0.2) for l, gt in zip(label_vector, gt_label_vector)], 0)
  File "/home/XXX/Documents/3D_Hier_Ins/grass_pytorch/grassmodel.py", line 227, in <listcomp>
    return torch.cat([self.creLoss(l.unsqueeze(0), gt).mul(0.2) for l, gt in zip(label_vector, gt_label_vector)], 0)
  File "/home/XXX/anaconda3/envs/Py36_PT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/XXX/anaconda3/envs/Py36_PT/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/XXX/anaconda3/envs/Py36_PT/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/XXX/anaconda3/envs/Py36_PT/lib/python3.6/site-packages/torch/nn/functional.py", line 1403, in nll_loss
    if input.size(0) != target.size(0):
RuntimeError: dimension specified as 0 but tensor has no dimensions
```
Any solutions? Thanks

**Comment by cyrushu** [comment]
try to change ~215 line in grassmodel.py
```python

    def boxLossEstimator(self, box_feature, gt_box_feature):
        return torch.cat([self.mseLoss(b, gt).mul(0.4).unsqueeze(0)
            for b, gt in zip(box_feature, gt_box_feature)], 0)

    def symLossEstimator(self, sym_param, gt_sym_param):
        return torch.cat([self.mseLoss(s, gt).mul(0.5).unsqueeze(0) for s, gt in zip(sym_param, gt_sym_param)], 0)

    def classifyLossEstimator(self, label_vector, gt_label_vector):
        loss = [self.creLoss(l.unsqueeze(0), gt.unsqueeze(0)).mul(0.2).unsqueeze(0) for l, gt in zip(label_vector, gt_label_vector)]
        return torch.cat(loss, 0)
```

and change train.py
~119 lines
```python
            print(log_template.format(strftime("%H:%M:%S",time.gmtime(time.time()-start)),
                epoch, config.epochs, 1+batch_idx, len(train_iter),
                100. * (1+batch_idx+len(train_iter)*epoch) / (len(train_iter)*config.epochs),
                recon_loss.item(), kldiv_loss.item(), total_loss.item()))
```

python train.py --no_plot will do it.

**Comment by kevin-kaixu** [comment]
Thanks, Yiliang, for the response.

**Comment by cyrushu** [comment]
@kevin-kaixu  The code is well structured and friendly to be read. The error mentioned is caused by the different version of pytorch.

**Comment by kevin-kaixu** [comment]
Thanks!
